### ISSUE TITLE
won't open

### ISSUE THREAD

**Issue by IrenvanderBeekPXL** [zhelyabuzhsky/stockfish#41]
Hello

I am trying to use your program inside my own program, but it craches with the following error:

Traceback (most recent call last):
  File "c:/Users/12000780/PycharmProjects/PyGames/schaken/main.py", line 10, in <module>
    engine = Stockfish("C:/Users/" + user + "/PycharmProjects/PyGames/schaken/stockfish-win")
  File "C:\Users\12000780\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\stockfish\models.py", line 33, in __init__
    self.stockfish = subprocess.Popen(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
PermissionError: [WinError 5] Toegang geweigerd
Exception ignored in: <function Stockfish.__del__ at 0x0000019442330820>
Traceback (most recent call last):
  File "C:\Users\12000780\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\stockfish\models.py", line 270, in __del__
    self.stockfish.kill()
AttributeError: 'Stockfish' object has no attribute 'stockfish'

I am using Python 3.8 and Windows. Could it be that it only works in Linux?

Thanks

**Comment by 2kofawsome** [comment]
Check out #32, you probably need "stockfish-win.exe"

**Comment by IrenvanderBeekPXL** [comment]
Thanks, I will try it out

**Comment by IrenvanderBeekPXL** [comment]
Thank you, it works
