### ISSUE TITLE
some permission issue on CentOS and MacOS.

### ISSUE THREAD

**Issue by aze2201** [zhelyabuzhsky/stockfish#5]
>>> stockfish = stockfish.Stockfish()
Exception ignored in: <bound method Stockfish.__del__ of <stockfish.Stockfish object at 0x7fa010ab1cf8>>
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/stockfish.py", line 140, in __del__
    self.stockfish.kill()
AttributeError: 'Stockfish' object has no attribute 'stockfish'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.4/site-packages/stockfish.py", line 27, in __init__
    stdout=subprocess.PIPE
  File "/usr/lib64/python3.4/subprocess.py", line 856, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.4/subprocess.py", line 1464, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'stockfish'

**Comment by zhelyabuzhsky** [comment]
Hello

You should install the stockfish engine in your operating system globally or specify the path to the binary file in the class constructor.
For example, `stockfish = Stockfish('/Users/zhelyabuzhsky/Work/stockfish/stockfish-9-64')`
